name: gauntlet-release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  release-gauntlet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gauntlet Build
        run: cd $GITHUB_WORKSPACE/gauntlet && yarn && yarn bundle
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            $GITHUB_WORKSPACE/gauntlet/bin/gauntlet-*
